# Generated by Django 5.0.1 on 2024-02-26 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='equipment',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='gym.equipments',
            ),
        ),
        migrations.AlterField(
            model_name='workouthistory',
            name='workout',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='gym.workouts'
            ),
        ),
    ]
