# Generated by Django 5.0.1 on 2024-03-18 23:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('gym', '0003_alter_workouts_options_workouts_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workouthistory',
            old_name='date',
            new_name='executed_at',
        ),
    ]
