# Generated by Django 5.0.1 on 2024-03-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gym', '0004_rename_date_workouthistory_executed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouthistory',
            name='executed_at',
            field=models.DateTimeField(),
        ),
    ]
