# Generated by Django 5.0.1 on 2024-03-21 23:23

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gym', '0005_alter_workouthistory_executed_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workouthistory',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='workouthistory',
            name='executed_at',
        ),
        migrations.RemoveField(
            model_name='workouthistory',
            name='repetitions',
        ),
        migrations.RemoveField(
            model_name='workouthistory',
            name='weight',
        ),
        migrations.AddField(
            model_name='workouthistory',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipments',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='musclegroups',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workouts',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EquipmentMuscleGroups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                (
                    'uuid',
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'equipment',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='gym.equipments',
                    ),
                ),
                (
                    'muscle_group',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='gym.musclegroups',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Equipment Muscle Group',
                'verbose_name_plural': 'Equipment Muscle Groups',
                'default_related_name': 'equipment_muscle_groups',
            },
        ),
        migrations.CreateModel(
            name='ExerciseMuscleGroups',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                (
                    'uuid',
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'exercise',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='gym.exercises',
                    ),
                ),
                (
                    'muscle_group',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='gym.musclegroups',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Exercise Muscle Group',
                'verbose_name_plural': 'Exercise Muscle Groups',
                'default_related_name': 'exercise_muscle_groups',
            },
        ),
        migrations.CreateModel(
            name='WorkoutExercises',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                (
                    'uuid',
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repetitions', models.PositiveIntegerField(null=True)),
                ('sets', models.PositiveIntegerField(null=True)),
                ('rest_period', models.DurationField(null=True)),
                (
                    'exercise',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='gym.exercises',
                    ),
                ),
                (
                    'workout',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='gym.workouts',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Workout Exercise',
                'verbose_name_plural': 'Workouts Exercises',
                'default_related_name': 'workout_exercises',
            },
        ),
        migrations.CreateModel(
            name='WorkoutHistoryExercises',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                (
                    'uuid',
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repetitions', models.PositiveIntegerField(null=True)),
                ('sets', models.PositiveIntegerField(null=True)),
                ('rest_period', models.DurationField(null=True)),
                (
                    'exercise',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='gym.exercises',
                    ),
                ),
                (
                    'workout_history',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='gym.workouthistory',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Workout History Exercise',
                'verbose_name_plural': 'Workout History Exercises',
                'default_related_name': 'workout_history_exercises',
            },
        ),
    ]
