# Generated by Django 5.0.1 on 2024-03-28 00:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gym', '0007_alter_equipmentmusclegroups_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workouthistory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workouthistory',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
