# Generated by Django 5.0.1 on 2024-04-04 00:16

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gym', '0008_workouthistory_description_workouthistory_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muscles',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                (
                    'uuid',
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Muscle',
                'verbose_name_plural': 'Muscles',
                'db_table': 'muscles',
                'default_related_name': 'muscles',
            },
        ),
    ]
