# Generated by Django 5.0.1 on 2024-04-05 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gym', '0010_alter_muscles_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='primary_muscle',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='primary_muscle',
                to='gym.muscles',
            ),
        ),
        migrations.AddField(
            model_name='exercises',
            name='secondary_muscle',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='secondary_muscle',
                to='gym.muscles',
            ),
        ),
    ]
