# Generated by Django 5.0.1 on 2024-04-05 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gym', '0011_exercises_primary_muscle_exercises_secondary_muscle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='primary_muscle',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='primary_muscle_group',
                to='gym.musclegroups',
            ),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='secondary_muscle',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='secondary_muscle_group',
                to='gym.musclegroups',
            ),
        ),
    ]
