# Generated by Django 5.0.1 on 2024-04-05 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gym', '0012_alter_exercises_primary_muscle_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Muscles',
        ),
        migrations.RemoveField(
            model_name='exercises',
            name='equipment',
        ),
        migrations.AddField(
            model_name='exercises',
            name='has_equipment',
            field=models.BooleanField(default=False),
        ),
    ]
