# Generated by Django 5.0.1 on 2024-04-07 01:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gym', '0014_rename_has_equipment_exercises_use_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musclegroups',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='musclegroups',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterModelTable(
            name='workoutexercises',
            table='workout_efrom django.utils.translation import gettext_lazy as _xercises',
        ),
    ]
