# Generated by Django 5.0.1 on 2024-04-07 01:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('gym', '0016_alter_workoutexercises_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutexercises',
            name='rest_period',
        ),
        migrations.RemoveField(
            model_name='workouthistoryexercises',
            name='rest_period',
        ),
    ]
