# Generated by Django 5.0.1 on 2024-04-17 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gym', '0018_workouthistory_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisemusclegroups',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='exercisemusclegroups',
            name='muscle_group',
        ),
        migrations.AlterField(
            model_name='workouthistory',
            name='workout',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='gym.workouts',
            ),
        ),
        migrations.DeleteModel(
            name='EquipmentMuscleGroups',
        ),
        migrations.DeleteModel(
            name='ExerciseMuscleGroups',
        ),
    ]
