# Generated by Django 5.0.1 on 2024-04-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gym', '0019_remove_exercisemusclegroups_exercise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workouthistoryexercises',
            name='exercise_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
