# Generated by Django 5.0.1 on 2024-04-19 10:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('gym', '0020_workouthistoryexercises_exercise_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workouthistory',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='workouthistory',
            name='duration',
        ),
    ]
