# Generated by Django 5.0.1 on 2024-04-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gym', '0024_workouts_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexercises',
            name='rest_period',
            field=models.IntegerField(null=True),
        ),
    ]
