# Generated by Django 5.0.1 on 2024-04-25 21:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('gym', '0025_workoutexercises_rest_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workouts',
            old_name='name',
            new_name='title',
        ),
    ]
