# Generated by Django 5.0.1 on 2024-04-26 23:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gym', '0027_rename_name_workouthistory_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='workouthistoryexercises',
            name='rest_period',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='workouthistoryexercises',
            name='weight_in_kg',
            field=models.IntegerField(null=True),
        ),
    ]
