# Generated by Django 5.0.1 on 2024-05-03 22:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('gym', '0029_gyminstructor_gymmember'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GymInstructor',
        ),
        migrations.DeleteModel(
            name='GymMember',
        ),
    ]
