# Generated by Django 5.0.7 on 2024-07-26 10:48

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipments',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipments',
                'db_table': 'equipments',
                'default_related_name': 'equipments',
            },
        ),
        migrations.CreateModel(
            name='MuscleGroups',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                (
                    'description',
                    models.TextField(null=True, verbose_name='description'),
                ),
            ],
            options={
                'verbose_name': 'Muscle Group',
                'verbose_name_plural': 'Muscle Groups',
                'db_table': 'muscle_groups',
                'default_related_name': 'muscle_groups',
            },
        ),
        migrations.CreateModel(
            name='Exercises',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('use_equipment', models.BooleanField(default=False)),
                (
                    'primary_muscle',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='primary_muscle_group',
                        to='gym.musclegroups',
                    ),
                ),
                (
                    'secondary_muscle',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='secondary_muscle_group',
                        to='gym.musclegroups',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Exercise',
                'verbose_name_plural': 'Exercises',
                'db_table': 'exercises',
                'default_related_name': 'exercises',
            },
        ),
        migrations.CreateModel(
            name='WorkoutHistory',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Workout History',
                'verbose_name_plural': 'Workout Historys',
                'db_table': 'workout_history',
                'default_related_name': 'workout_history',
            },
        ),
        migrations.CreateModel(
            name='WorkoutHistoryExercises',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repetitions', models.PositiveIntegerField(null=True)),
                ('sets', models.PositiveIntegerField(null=True)),
                (
                    'exercise_name',
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ('weight_in_kg', models.IntegerField(null=True)),
                ('rest_period', models.IntegerField(null=True)),
                (
                    'exercise',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='gym.exercises',
                    ),
                ),
                (
                    'workout_history',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='gym.workouthistory',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Workout History Exercise',
                'verbose_name_plural': 'Workout History Exercises',
                'db_table': 'workout_history_exercises',
                'default_related_name': 'workout_history_exercises',
            },
        ),
        migrations.CreateModel(
            name='Workouts',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='created_by',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Workout',
                'verbose_name_plural': 'Workouts',
                'db_table': 'workouts',
                'default_related_name': 'workouts',
            },
        ),
        migrations.AddField(
            model_name='workouthistory',
            name='workout',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='gym.workouts',
            ),
        ),
        migrations.CreateModel(
            name='WorkoutExercises',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repetitions', models.PositiveIntegerField(null=True)),
                ('sets', models.PositiveIntegerField(null=True)),
                ('weight_in_kg', models.IntegerField(null=True)),
                ('rest_period', models.IntegerField(null=True)),
                (
                    'exercise',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='gym.exercises',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'workout',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='gym.workouts',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Workout Exercise',
                'verbose_name_plural': 'Workouts Exercises',
                'db_table': 'workout_exercises',
                'default_related_name': 'workout_exercises',
            },
        ),
    ]
