# Generated by Django 5.0.7 on 2024-07-29 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gym', '0006_rename_weight_in_kg_workouthistoryexercises_weight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workouthistory',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='history_created_by',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
