# Generated by Django 5.0.7 on 2024-08-26 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gym', '0011_remove_workouthistory_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercises',
            name='use_equipment',
        ),
        migrations.AddField(
            model_name='exercises',
            name='equipment',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='gym.equipments',
                verbose_name='equipment',
            ),
        ),
    ]
