# Generated by Django 5.0.7 on 2024-08-28 00:42

import functools

from django.db import migrations, models

import apps.core.utils


class Migration(migrations.Migration):
    dependencies = [
        ('gym', '0013_equipments_translations_musclegroups_translations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musclegroups',
            name='translations',
            field=models.JSONField(
                default=functools.partial(
                    apps.core.utils.default_translation, *('name', 'description'), **{}
                ),
                verbose_name='translation',
            ),
        ),
    ]
