# Generated by Django 5.0.7 on 2024-08-28 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gym', '0016_exercises_translations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercises',
            name='equipment',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='gym.equipments',
                verbose_name='equipment',
            ),
        ),
    ]
