# Generated by Django 5.0.7 on 2024-08-29 23:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gym', '0017_alter_exercises_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musclegroups',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
    ]
