# Generated by Django 5.0.7 on 2024-08-29 23:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gym', '0018_alter_musclegroups_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musclegroups',
            name='name',
            field=models.JSONField(null=True, verbose_name='name'),
        ),
    ]
