# Generated by Django 5.0.7 on 2024-08-30 00:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('gym', '0020_alter_musclegroups_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musclegroups',
            name='translations',
        ),
    ]
