# Generated by Django 5.0.7 on 2024-08-30 00:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('gym', '0021_remove_musclegroups_translations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipments',
            name='description',
        ),
        migrations.RemoveField(
            model_name='equipments',
            name='name',
        ),
    ]
