# Generated by Django 5.0.7 on 2024-08-30 00:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gym', '0022_remove_equipments_description_remove_equipments_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipments',
            name='description',
            field=models.JSONField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='equipments',
            name='name',
            field=models.JSONField(null=True, verbose_name='name'),
        ),
    ]
