# Generated by Django 5.0.7 on 2024-08-30 00:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gym', '0024_remove_exercises_description_remove_exercises_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercises',
            name='description',
            field=models.JSONField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='exercises',
            name='name',
            field=models.JSONField(null=True, verbose_name='name'),
        ),
    ]
