# Generated by Django 5.0.7 on 2024-08-30 01:24

from django.db import migrations, models

import apps.gym.validators


class Migration(migrations.Migration):
    dependencies = [
        ('gym', '0026_alter_equipments_description_alter_equipments_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipments',
            name='name',
            field=models.JSONField(
                validators=[apps.gym.validators.translated_field_validator],
                verbose_name='name',
            ),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='name',
            field=models.JSONField(
                validators=[apps.gym.validators.translated_field_validator],
                verbose_name='name',
            ),
        ),
        migrations.AlterField(
            model_name='musclegroups',
            name='name',
            field=models.JSONField(
                validators=[apps.gym.validators.translated_field_validator],
                verbose_name='name',
            ),
        ),
    ]
