# Generated by Django 5.0.7 on 2024-08-30 10:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('gym', '0027_alter_equipments_name_alter_exercises_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipments',
            name='translations',
        ),
        migrations.RemoveField(
            model_name='exercises',
            name='translations',
        ),
    ]
