# Generated by Django 5.0.7 on 2024-08-30 10:41

from django.db import migrations, models

import apps.core.utils
import apps.gym.validators


class Migration(migrations.Migration):
    dependencies = [
        ('gym', '0028_remove_equipments_translations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipments',
            name='description',
            field=models.JSONField(
                default=apps.core.utils.default_translation,
                null=True,
                validators=[apps.gym.validators.translated_field_validator],
                verbose_name='description',
            ),
        ),
        migrations.AlterField(
            model_name='equipments',
            name='name',
            field=models.JSONField(
                default=apps.core.utils.default_translation,
                validators=[apps.gym.validators.translated_field_validator],
                verbose_name='name',
            ),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='description',
            field=models.JSONField(
                default=apps.core.utils.default_translation,
                null=True,
                validators=[apps.gym.validators.translated_field_validator],
                verbose_name='description',
            ),
        ),
        migrations.AlterField(
            model_name='exercises',
            name='name',
            field=models.JSONField(
                default=apps.core.utils.default_translation,
                validators=[apps.gym.validators.translated_field_validator],
                verbose_name='name',
            ),
        ),
        migrations.AlterField(
            model_name='musclegroups',
            name='description',
            field=models.JSONField(
                default=apps.core.utils.default_translation,
                null=True,
                validators=[apps.gym.validators.translated_field_validator],
                verbose_name='description',
            ),
        ),
        migrations.AlterField(
            model_name='musclegroups',
            name='name',
            field=models.JSONField(
                default=apps.core.utils.default_translation,
                validators=[apps.gym.validators.translated_field_validator],
                verbose_name='name',
            ),
        ),
    ]
