# Generated by Django 5.0.7 on 2024-08-31 23:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gym', '0030_alter_equipments_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutexercises',
            name='repetitions',
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name='repetitions'
            ),
        ),
        migrations.AlterField(
            model_name='workoutexercises',
            name='rest_period',
            field=models.IntegerField(default=0, null=True, verbose_name='rest period'),
        ),
        migrations.AlterField(
            model_name='workoutexercises',
            name='sets',
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name='sets'
            ),
        ),
        migrations.AlterField(
            model_name='workoutexercises',
            name='weight',
            field=models.IntegerField(default=0, null=True, verbose_name='weight'),
        ),
        migrations.AlterField(
            model_name='workouthistoryexercises',
            name='rest_period',
            field=models.IntegerField(default=0, null=True, verbose_name='rest period'),
        ),
        migrations.AlterField(
            model_name='workouthistoryexercises',
            name='sets',
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name='sets'
            ),
        ),
        migrations.AlterField(
            model_name='workouthistoryexercises',
            name='weight',
            field=models.IntegerField(default=0, null=True, verbose_name='weight'),
        ),
    ]
