# Generated by Django 5.0.7 on 2024-09-04 23:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gym', '0031_alter_workoutexercises_repetitions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutexercises',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
    ]
