# Generated by Django 5.0.7 on 2024-09-25 17:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('gym', '0032_workoutexercises_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workouthistory',
            name='creator',
        ),
    ]
