# Generated by Django 5.0.7 on 2024-09-26 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gym', '0034_workouthistory_creator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouthistory',
            name='creator',
            field=models.ForeignKey(
                blank=True,
                help_text='The user who created the completed workout',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='history_creator',
                to=settings.AUTH_USER_MODEL,
                verbose_name='creator',
            ),
        ),
        migrations.AlterField(
            model_name='workouthistory',
            name='user',
            field=models.ForeignKey(
                blank=True,
                help_text='The user who the completed workout',
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
                verbose_name='user',
            ),
        ),
    ]
