# Generated by Django 5.0.7 on 2024-09-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gym', '0035_alter_workouthistory_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workouthistoryexercises',
            name='is_done',
            field=models.BooleanField(default=False, verbose_name='is completed'),
        ),
    ]
