# Generated by Django 5.0.7 on 2024-09-27 21:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('gym', '0036_workouthistoryexercises_is_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workouthistoryexercises',
            name='name',
        ),
    ]
