# Generated by Django 5.0.7 on 2024-11-26 16:37

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gym', '0037_remove_workouthistoryexercises_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equipments',
            new_name='Equipment',
        ),
        migrations.RenameModel(
            old_name='Exercises',
            new_name='Exercise',
        ),
        migrations.RenameModel(
            old_name='MuscleGroups',
            new_name='MuscleGroup',
        ),
        migrations.RenameModel(
            old_name='Workouts',
            new_name='Workout',
        ),
        migrations.RenameModel(
            old_name='WorkoutExercises',
            new_name='WorkoutExercise',
        ),
        migrations.CreateModel(
            name='WorkoutExerciseSets',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'repetitions',
                    models.PositiveIntegerField(
                        default=0, null=True, verbose_name='repetitions'
                    ),
                ),
                (
                    'weight',
                    models.PositiveIntegerField(
                        default=0, null=True, verbose_name='weight'
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='user',
                    ),
                ),
                (
                    'workout_exercise',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='gym.workoutexercise',
                        verbose_name='workout exercise',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Workout Exercise Set',
                'verbose_name_plural': 'Workout Exercise Sets',
                'db_table': 'workout_exercise_sets',
                'default_related_name': 'workout_exercise_sets',
            },
        ),
        migrations.CreateModel(
            name='WorkoutHistorySets',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'repetitions',
                    models.PositiveIntegerField(
                        default=0, null=True, verbose_name='repetitions'
                    ),
                ),
                (
                    'weight',
                    models.PositiveIntegerField(
                        default=0, null=True, verbose_name='weight'
                    ),
                ),
                (
                    'is_done',
                    models.BooleanField(default=False, verbose_name='is completed'),
                ),
                (
                    'user',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='user',
                    ),
                ),
                (
                    'workout_history_exercise',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='gym.workouthistoryexercises',
                        verbose_name='workout history exercise',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Workout History Set',
                'verbose_name_plural': 'Workout History Sets',
                'db_table': 'workout_history_sets',
                'default_related_name': 'workout_history_sets',
            },
        ),
    ]
