# Generated by Django 5.0.1 on 2024-02-20 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_birth_date_users_first_name_users_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='document',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True),
        ),
    ]
