# Generated by Django 5.0.1 on 2024-04-05 01:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0004_alter_users_date_joined_alter_users_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='users',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='height'),
        ),
        migrations.AddField(
            model_name='users',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='weight'),
        ),
        migrations.AlterModelTable(
            name='users',
            table='users',
        ),
    ]
