# Generated by Django 5.0.1 on 2024-05-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0005_alter_users_options_users_height_users_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(
                choices=[
                    ('gym_member', 'Gym Member'),
                    ('gym_instructor', 'Gym Instructor'),
                ],
                default='gym_member',
                max_length=15,
                verbose_name='role',
            ),
        ),
    ]
