# Generated by Django 5.0.7 on 2024-07-26 10:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('gym', '0003_alter_workoutexercises_exercise_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutexercises',
            old_name='weight_in_kg',
            new_name='weight',
        ),
    ]
