# Generated by Django 5.0.7 on 2024-07-29 10:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('gym', '0004_rename_weight_in_kg_workoutexercises_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workouthistoryexercises',
            old_name='exercise_name',
            new_name='name',
        ),
    ]
