# Generated by Django 5.0.7 on 2024-07-29 10:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('gym', '0005_rename_exercise_name_workouthistoryexercises_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workouthistoryexercises',
            old_name='weight_in_kg',
            new_name='weight',
        ),
    ]
