# Use the official PostgreSQL image from the Docker Hub as the base image
FROM postgres:latest

# Set environment variables
ENV POSTGRES_DB=database
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres

# Define the volume that will be used for storing database data
VOLUME ["/var/lib/postgresql/data"]

# Expose the port the server listens on
EXPOSE 5432