# Generated by Django 5.0.7 on 2024-07-26 10:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='uuid',
        ),
    ]
